esphome:
  name: esphome-co2

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

web_server:
  port: 80

# Example configuration entry
uart:
  rx_pin: GPIO14
  tx_pin: GPIO12
  baud_rate: 9600

sensor:
  - platform: mhz19
    co2:
      name: "CO2 Value"
      id: co2ppm
    temperature:
      name: "MH-Z19 Temperature"
    update_interval: 30s
    automatic_baseline_calibration: true
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 30s

i2c:
  sda: D1
  scl: D2
  frequency: 800kHz

font:
  - file: "gfonts://Roboto"
    id: small
    size: 16
  - file: "gfonts://Roboto@Bold"
    id: bold
    size: 24
  - file: 'fonts/SourceSansPro-Light.ttf'
    id: font1
    size: 14

time:
  - platform: homeassistant
    id: homeassistant_time

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: D0
    address: 0x3C
    update_interval: 1s
    lambda: |-
      it.printf(64, 2, id(small),  TextAlign::TOP_CENTER, "CO2 PPM");
      it.printf(64, 32, id(bold), TextAlign::CENTER, "%.0f", id(co2ppm).state);
      it.strftime(64, 62, id(font1), TextAlign::BASELINE_CENTER, "%H:%M:%S", id(homeassistant_time).now());

